apiVersion: v1
kind: Secret
metadata:
  name: {{ include "journal.fullname" . }}
  labels:
    {{- include "journal.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.url | quote }}
  session-password: {{ .Values.session.password | quote }}
  oidc-client-secret: {{ .Values.oidc.clientSecret | quote }}
