image:
  repository: localhost:5050/journal
  tag: latest
  pullPolicy: Always

database:
  url: "postgresql://journal:journal@journal-postgres:5432/journal"

ingress:
  enabled: false

resources:
  requests: null
  limits: null
